### ISSUE TITLE
XR_ERROR_RUNTIME_FAILURE, seems OpenXR for WMR doesn't work at all

### ISSUE THREAD

**Issue by PhMajerus** [maluoi/StereoKit#83] opened 2020-05-23 12:32 UTC
I guess this isn't directly because of StereoKit, but even the simplest cube .NET core project template fails to render anything.
OpenXR worked when initially released, but since months, probably around Windows 10 19H2 and still in 20H1, it doesn't work at all, it is installed and the OpenXR Developer Tools portal shows it is setup and ready, but the demo scene from that portal fails and StereoKit fails with [SK info] xrEndFrame [XR_ERROR_RUNTIME_FAILURE].

With no error shown by the OpenXR Developer Tools, it seems anything relying on OpenXR is simply unusable, which makes using any framework based on it a risky bet when UWP and SteamVR apps are all running fine.

Any idea of what might be wrong and if OpenXR is supposed to be ready for release?
Running on a Surface Book 2 15" build 19041.264 and OpenXR for WMR 101.2005.1005.0.

**Comment by maluoi** [comment] 2020-05-23 21:13
Heyas, thanks for the report!

This doesn't happen on my other machines, but I just tried this on my Surface Book 2 15", and I can confirm it does happen there. However, this is also the first time I've had a WMR headset boot properly on my Surface Book 2, so uhh... I'd call it a slight improvement! I've not been happy at all with how my Surface Book 2 handles, it's rough :( However, I've also never had OpenXR crash out on me entirely like this, so I don't have much experience troubleshooting this part! I'll look into it, and I'll float this one to the WMR OpenXR team and see if they have any insight on it!

In the meantime, it looks like I'm on a slightly older Windows build, 18363.836, but the same OpenXR for WMR. Though the OpenXR runtime version might be a better comparison there. If you check OpenXR Developer Tools -> System Status, what's your runtime version there? I'm at 100.2003.19009

**Comment by maluoi** [comment] 2020-05-23 21:36
Here's the exception I get along with this failure:

```
Exception thrown at 0x00007FFECDCEA799 in StereoKitTest.exe: Microsoft C++ exception: _com_error at memory location 0x00000044A29FD228.
Exception thrown at 0x00007FFECDCEA799 (KernelBase.dll) in StereoKitTest.exe: WinRT originate error - 0x80070057 : 'The provided value was outside of the range of valid values.'.
onecore\com\combase\winrt\error\restrictederror.cpp(1014)\combase.dll!00007FFECEE635B0: (caller: 00007FFECEE4CAEC) ReturnHr(11) tid(5650) 8007007E The specified module could not be found.
analog\input\mirage\publicapi\compositionlayerd3d12bufferprovider.cpp(201)\Windows.Mirage.dll!00007FFE6DC11E9A: (caller: 00007FFE6DB9FA25) ReturnHr(21) tid(5650) 80070057 The parameter is incorrect.
    Msg:[deviceAdapterLuid.LowPart == m_outputAdapterLuid.LowPart && deviceAdapterLuid.HighPart == m_outputAdapterLuid.HighPart] 
analog\input\mirage\publicapi\holographiccamera.cpp(531)\Windows.Mirage.dll!00007FFE6DB9FA43: (caller: 00007FFE6DB9F811) ReturnHr(22) tid(5650) 80070057 The parameter is incorrect.
Exception thrown at 0x00007FFECDCEA799 in StereoKitTest.exe: Microsoft C++ exception: winrt::hresult_invalid_argument at memory location 0x00000044A29FCD00.
```

Given the mention of LUID here, there's a good chance this is related to the fact that Surface Book 2 has 2 GPUs in it?

**Comment by gongminmin** [comment] 2020-06-17 22:08
We are investigating this issue in Microsoft OpenXR runtime. A fix will be provided soon. Thanks!

**Comment by maluoi** [comment] 2021-06-03 22:37
I believe this should be fixed and/or irrelevant by now, lots of improvements in related areas.

**Closed by maluoi** 2021-06-03 22:37 UTC
